# Module to Manage Redis and Sentinel
class redis (

  $package        = $redis::params::package,
  $service        = $redis::params::service,
  $conf           = $redis::params::conf,
  $conf_logrotate = $redis::params::conf_logrotate,
  $pidfile        = $redis::params::pidfile,
  $logfile        = $redis::params::logfile,
  $package_ensure = $redis::params::package_ensure,
  $service_ensure = $redis::params::service_ensure,

  $daemonize                         = $redis::params::daemonize,
  $port                              = $redis::params::port,
  $tcp_backlog                       = $redis::params::tcp_backlog,
  $bind                              = $redis::params::bind,
  $unixsocket                        = $redis::params::unixsocket,
  $timeout                           = $redis::params::timeout,
  $tcp_keepalive                     = $redis::params::tcp_keepalive,
  $loglevel                          = $redis::params::loglevel,
  $syslog_enabled                    = $redis::params::syslog_enabled,
  $syslog_ident                      = $redis::params::syslog_ident,
  $syslog_facility                   = $redis::params::syslog_facility,
  $databases                         = $redis::params::databases,
  $nosave                            = $redis::params::nosave,
  $save                              = $redis::params::save,
  $stop_writes_on_bgsave_error       = $redis::params::stop_writes_on_bgsave_error,
  $rdbcompression                    = $redis::params::rdbcompression,
  $rdbchecksum                       = $redis::params::rdbchecksum,
  $dbfilename                        = $redis::params::dbfilename,
  $dir                               = $redis::params::dir,
  $slaveof                           = $redis::params::slaveof,
  $masterauth                        = $redis::params::masterauth,
  $slave_serve_stale_data            = $redis::params::slave_serve_stale_data,
  $slave_read_only                   = $redis::params::slave_read_only,
  $repl_ping_slave_period            = $redis::params::repl_ping_slave_period,
  $repl_timeout                      = $redis::params::repl_timeout,
  $repl_disable_tcp_nodelay          = $redis::params::repl_disable_tcp_nodelay,
  $repl_backlog_size                 = $redis::params::repl_backlog_size,
  $repl_backlog_ttl                  = $redis::params::repl_backlog_ttl,
  $slave_priority                    = $redis::params::slave_priority,
  $min_slaves_to_write               = $redis::params::min_slaves_to_write,
  $min_slaves_max_lag                = $redis::params::min_slaves_max_lag,
  $requirepass                       = $redis::params::requirepass,
  $maxclients                        = $redis::params::maxclients,
  $maxmemory                         = $redis::params::maxmemory,
  $maxmemory_policy                  = $redis::params::maxmemory_policy,
  $maxmemory_samples                 = $redis::params::maxmemory_samples,
  $appendonly                        = $redis::params::appendonly,
  $appendfilename                    = $redis::params::appendfilename,
  $appendfsync                       = $redis::params::appendfsync,
  $no_appendfsync_on_rewrite         = $redis::params::no_appendfsync_on_rewrite,
  $auto_aof_rewrite_percentage       = $redis::params::auto_aof_rewrite_percentage,
  $auto_aof_rewrite_min_size         = $redis::params::auto_aof_rewrite_min_size,
  $aof_load_truncated                = $redis::params::aof_load_truncated,
  $lua_time_limit                    = $redis::params::lua_time_limit,
  $slowlog_log_slower_than           = $redis::params::slowlog_log_slower_than,
  $slowlog_max_len                   = $redis::params::slowlog_max_len,
  $latency_monitor_threshold         = $redis::params::latency_monitor_threshold,
  $notify_keyspace_events            = $redis::params::notify_keyspace_events,
  $hash_max_zipmap_entries           = $redis::params::hash_max_zipmap_entries,
  $hash_max_zipmap_value             = $redis::params::hash_max_zipmap_value,
  $list_max_ziplist_entries          = $redis::params::list_max_ziplist_entries,
  $list_max_ziplist_value            = $redis::params::list_max_ziplist_value,
  $set_max_intset_entries            = $redis::params::set_max_intset_entries,
  $zset_max_ziplist_entries          = $redis::params::zset_max_ziplist_entries,
  $zset_max_ziplist_value            = $redis::params::zset_max_ziplist_value,
  $hll_sparse_max_bytes              = $redis::params::hll_sparse_max_bytes,
  $activerehashing                   = $redis::params::activerehashing,
  $client_output_buffer_limit_normal = $redis::params::client_output_buffer_limit_normal,
  $client_output_buffer_limit_slave  = $redis::params::client_output_buffer_limit_slave,
  $client_output_buffer_limit_pubsub = $redis::params::client_output_buffer_limit_pubsub,
  $hz                                = $redis::params::hz,
  $aof_rewrite_incremental_fsync     = $redis::params::aof_rewrite_incremental_fsync,

) inherits redis::params {

  contain '::redis::install'

  class { '::redis::config':
    daemonize                         => $redis::daemonize,
    port                              => $redis::port,
    tcp_backlog                       => $redis::tcp_backlog,
    bind                              => $redis::bind,
    unixsocket                        => $redis::unixsocket,
    timeout                           => $redis::timeout,
    tcp_keepalive                     => $redis::tcp_keepalive,
    loglevel                          => $redis::loglevel,
    syslog_enabled                    => $redis::syslog_enabled,
    syslog_ident                      => $redis::syslog_ident,
    syslog_facility                   => $redis::syslog_facility,
    databases                         => $redis::databases,
    nosave                            => $redis::nosave,
    save                              => $redis::save,
    stop_writes_on_bgsave_error       => $redis::stop_writes_on_bgsave_error,
    rdbcompression                    => $redis::rdbcompression,
    rdbchecksum                       => $redis::rdbchecksum,
    dbfilename                        => $redis::dbfilename,
    dir                               => $redis::dir,
    slaveof                           => $redis::slaveof,
    masterauth                        => $redis::masterauth,
    slave_serve_stale_data            => $redis::slave_serve_stale_data,
    slave_read_only                   => $redis::slave_read_only,
    repl_ping_slave_period            => $redis::repl_ping_slave_period,
    repl_timeout                      => $redis::repl_timeout,
    repl_disable_tcp_nodelay          => $redis::repl_disable_tcp_nodelay,
    repl_backlog_size                 => $redis::repl_backlog_size,
    repl_backlog_ttl                  => $redis::repl_backlog_ttl,
    slave_priority                    => $redis::slave_priority,
    min_slaves_to_write               => $redis::min_slaves_to_write,
    min_slaves_max_lag                => $redis::min_slaves_max_lag,
    requirepass                       => $redis::requirepass,
    maxclients                        => $redis::maxclients,
    maxmemory                         => $redis::maxmemory,
    maxmemory_policy                  => $redis::maxmemory_policy,
    maxmemory_samples                 => $redis::maxmemory_samples,
    appendonly                        => $redis::appendonly,
    appendfilename                    => $redis::appendfilename,
    appendfsync                       => $redis::appendfsync,
    no_appendfsync_on_rewrite         => $redis::no_appendfsync_on_rewrite,
    auto_aof_rewrite_percentage       => $redis::auto_aof_rewrite_percentage,
    auto_aof_rewrite_min_size         => $redis::auto_aof_rewrite_min_size,
    aof_load_truncated                => $redis::aof_load_truncated,
    lua_time_limit                    => $redis::lua_time_limit,
    slowlog_log_slower_than           => $redis::slowlog_log_slower_than,
    slowlog_max_len                   => $redis::slowlog_max_len,
    latency_monitor_threshold         => $redis::latency_monitor_threshold,
    notify_keyspace_events            => $redis::notify_keyspace_events,
    hash_max_zipmap_entries           => $redis::hash_max_zipmap_entries,
    hash_max_zipmap_value             => $redis::hash_max_zipmap_value,
    list_max_ziplist_entries          => $redis::list_max_ziplist_entries,
    list_max_ziplist_value            => $redis::list_max_ziplist_value,
    set_max_intset_entries            => $redis::set_max_intset_entries,
    zset_max_ziplist_entries          => $redis::zset_max_ziplist_entries,
    zset_max_ziplist_value            => $redis::zset_max_ziplist_value,
    hll_sparse_max_bytes              => $redis::hll_sparse_max_bytes,
    activerehashing                   => $redis::activerehashing,
    client_output_buffer_limit_normal => $redis::client_output_buffer_limit_normal,
    client_output_buffer_limit_slave  => $redis::client_output_buffer_limit_slave,
    client_output_buffer_limit_pubsub => $redis::client_output_buffer_limit_pubsub,
    hz                                => $redis::hz,
    aof_rewrite_incremental_fsync     => $redis::aof_rewrite_incremental_fsync
  }
  contain '::redis::config'

  contain '::redis::service'

  Class['::redis::install']->
  Class['::redis::config']~>
  Class['::redis::service']

}
